#pragma once
#include"../JGraphicResourceType.h"
#include<dxgiformat.h>

namespace JinEngine
{
	namespace Graphic
	{
		class JDx12Format
		{
		private:
			static constexpr uint undefinedFormatOffset = 4096;
		public:
			static uint DetermineElementSize(const DXGI_FORMAT format)
			{
				switch (format)
				{
				case DXGI_FORMAT_UNKNOWN:
					return 1;
				case DXGI_FORMAT_R32G32B32A32_TYPELESS:
				case DXGI_FORMAT_R32G32B32A32_FLOAT:
				case DXGI_FORMAT_R32G32B32A32_UINT:
				case DXGI_FORMAT_R32G32B32A32_SINT:
					return 16;
				case DXGI_FORMAT_R32G32B32_TYPELESS:
				case DXGI_FORMAT_R32G32B32_FLOAT:
				case DXGI_FORMAT_R32G32B32_UINT:
				case DXGI_FORMAT_R32G32B32_SINT:
					return 12;
				case DXGI_FORMAT_R16G16B16A16_TYPELESS:
				case DXGI_FORMAT_R16G16B16A16_FLOAT:
				case DXGI_FORMAT_R16G16B16A16_UNORM:
				case DXGI_FORMAT_R16G16B16A16_UINT:
				case DXGI_FORMAT_R16G16B16A16_SNORM:
				case DXGI_FORMAT_R16G16B16A16_SINT:
					return 8;
				case DXGI_FORMAT_R32G32_TYPELESS:
				case DXGI_FORMAT_R32G32_FLOAT:
				case DXGI_FORMAT_R32G32_UINT:
				case DXGI_FORMAT_R32G32_SINT:
				case DXGI_FORMAT_R32G8X24_TYPELESS:
				case DXGI_FORMAT_D32_FLOAT_S8X24_UINT:
				case DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS:
				case DXGI_FORMAT_X32_TYPELESS_G8X24_UINT:
					return 8;
				case DXGI_FORMAT_R10G10B10A2_TYPELESS:
				case DXGI_FORMAT_R10G10B10A2_UNORM:
				case DXGI_FORMAT_R10G10B10A2_UINT:
				case DXGI_FORMAT_R11G11B10_FLOAT:
				case DXGI_FORMAT_R8G8B8A8_TYPELESS:
				case DXGI_FORMAT_R8G8B8A8_UNORM:
				case DXGI_FORMAT_R8G8B8A8_UNORM_SRGB:
				case DXGI_FORMAT_R8G8B8A8_UINT:
				case DXGI_FORMAT_R8G8B8A8_SNORM:
				case DXGI_FORMAT_R8G8B8A8_SINT:
				case DXGI_FORMAT_R16G16_TYPELESS:
				case DXGI_FORMAT_R16G16_FLOAT:
				case DXGI_FORMAT_R16G16_UNORM:
				case DXGI_FORMAT_R16G16_UINT:
				case DXGI_FORMAT_R16G16_SNORM:
				case DXGI_FORMAT_R16G16_SINT:
				case DXGI_FORMAT_R32_TYPELESS:
				case DXGI_FORMAT_D32_FLOAT:
				case DXGI_FORMAT_R32_FLOAT:
				case DXGI_FORMAT_R32_UINT:
				case DXGI_FORMAT_R32_SINT:
				case DXGI_FORMAT_R24G8_TYPELESS:
				case DXGI_FORMAT_D24_UNORM_S8_UINT:
				case DXGI_FORMAT_R24_UNORM_X8_TYPELESS:
				case DXGI_FORMAT_X24_TYPELESS_G8_UINT:
					return 4;
				case DXGI_FORMAT_R8G8_TYPELESS:
				case DXGI_FORMAT_R8G8_UNORM:
				case DXGI_FORMAT_R8G8_UINT:
				case DXGI_FORMAT_R8G8_SNORM:
				case DXGI_FORMAT_R8G8_SINT:
				case DXGI_FORMAT_R16_TYPELESS:
				case DXGI_FORMAT_R16_FLOAT:
				case DXGI_FORMAT_D16_UNORM:
				case DXGI_FORMAT_R16_UNORM:
				case DXGI_FORMAT_R16_UINT:
				case DXGI_FORMAT_R16_SNORM:
				case DXGI_FORMAT_R16_SINT:
					return 2;
				case DXGI_FORMAT_R8_TYPELESS:
				case DXGI_FORMAT_R8_UNORM:
				case DXGI_FORMAT_R8_UINT:
				case DXGI_FORMAT_R8_SNORM:
				case DXGI_FORMAT_R8_SINT:
				case DXGI_FORMAT_A8_UNORM:
					return 1;
				case DXGI_FORMAT_R1_UNORM:
					return 1;
				case DXGI_FORMAT_R9G9B9E5_SHAREDEXP:
				case DXGI_FORMAT_R8G8_B8G8_UNORM:
				case DXGI_FORMAT_G8R8_G8B8_UNORM:
					return 4;
				case DXGI_FORMAT_B5G6R5_UNORM:
				case DXGI_FORMAT_B5G5R5A1_UNORM:
					return 2;
				case DXGI_FORMAT_B8G8R8A8_UNORM:
				case DXGI_FORMAT_B8G8R8X8_UNORM:
				case DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM:
				case DXGI_FORMAT_B8G8R8A8_TYPELESS:
				case DXGI_FORMAT_B8G8R8A8_UNORM_SRGB:
				case DXGI_FORMAT_B8G8R8X8_TYPELESS:
				case DXGI_FORMAT_B8G8R8X8_UNORM_SRGB:
					return 4;
				default:
					return 1;		//unkown
				}
			}
			static DXGI_FORMAT ConvertApi(const J_GRAPHIC_RESOURCE_FORMAT format)
			{
				switch (format)
				{
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::API_SPECIALIZED:
					return DXGI_FORMAT_UNKNOWN;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R32G32B32A32_FLOAT:
					return DXGI_FORMAT_R32G32B32A32_FLOAT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R32G32B32A32_UINT:
					return DXGI_FORMAT_R32G32B32A32_UINT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R32G32B32A32_SINT:
					return DXGI_FORMAT_R32G32B32A32_SINT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R32G32B32_FLOAT:
					return DXGI_FORMAT_R32G32B32_FLOAT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R32G32B32_UINT:
					return DXGI_FORMAT_R32G32B32_UINT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R32G32B32_SINT:
					return DXGI_FORMAT_R32G32B32_SINT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R16G16B16A16_FLOAT:
					return DXGI_FORMAT_R16G16B16A16_FLOAT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R16G16B16A16_UNORM:
					return DXGI_FORMAT_R16G16B16A16_UNORM;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R16G16B16A16_UINT:
					return DXGI_FORMAT_R16G16B16A16_UINT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R16G16B16A16_SNORM:
					return DXGI_FORMAT_R16G16B16A16_SNORM;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R16G16B16A16_SINT:
					return DXGI_FORMAT_R16G16B16A16_SINT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R32G32_FLOAT:
					return DXGI_FORMAT_R32G32_FLOAT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R32G32_UINT:
					return DXGI_FORMAT_R32G32_UINT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R32G32_SINT:
					return DXGI_FORMAT_R32G32_SINT; 
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R10G10B10A2_UNORM:
					return DXGI_FORMAT_R10G10B10A2_UNORM;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R10G10B10A2_UINT:
					return DXGI_FORMAT_R10G10B10A2_UINT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R11G11B10_FLOAT:
					return DXGI_FORMAT_R11G11B10_FLOAT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R8G8B8A8_UNORM:
					return DXGI_FORMAT_R8G8B8A8_UNORM;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R8G8B8A8_UNORM_SRGB:
					return DXGI_FORMAT_R8G8B8A8_UNORM_SRGB;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R8G8B8A8_UINT:
					return DXGI_FORMAT_R8G8B8A8_UINT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R8G8B8A8_SNORM:
					return DXGI_FORMAT_R8G8B8A8_SNORM;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R8G8B8A8_SINT:
					return DXGI_FORMAT_R8G8B8A8_SINT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R16G16_FLOAT:
					return DXGI_FORMAT_R16G16_FLOAT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R16G16_UNORM:
					return DXGI_FORMAT_R16G16_UNORM;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R16G16_UINT:
					return DXGI_FORMAT_R16G16_UINT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R16G16_SNORM:
					return DXGI_FORMAT_R16G16_SNORM;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R16G16_SINT:
					return DXGI_FORMAT_R16G16_SINT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::D32_FLOAT:
					return DXGI_FORMAT_D32_FLOAT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R32_FLOAT:
					return DXGI_FORMAT_R32_FLOAT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R32_UINT:
					return DXGI_FORMAT_R32_UINT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R32_SINT:
					return DXGI_FORMAT_R32_SINT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::D24_S8:
					return DXGI_FORMAT_R24_UNORM_X8_TYPELESS;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R8G8_UNORM:
					return DXGI_FORMAT_R8G8_UNORM;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R8G8_UINT:
					return DXGI_FORMAT_R8G8_UINT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R8G8_SNORM:
					return DXGI_FORMAT_R8G8_SNORM;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R8G8_SINT:
					return DXGI_FORMAT_R8G8_SINT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R16_FLOAT:
					return DXGI_FORMAT_R16_FLOAT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::D16_UNORM:
					return DXGI_FORMAT_D16_UNORM;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R16_UNORM:
					return DXGI_FORMAT_R16_UNORM;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R16_UINT:
					return DXGI_FORMAT_R16_UINT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R16_SNORM:
					return DXGI_FORMAT_R16_SNORM;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R16_SINT:
					return DXGI_FORMAT_R16_SINT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R8_UNORM:
					return DXGI_FORMAT_R8_UNORM;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R8_UINT:
					return DXGI_FORMAT_R8_UINT;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R8_SNORM:
					return DXGI_FORMAT_R8_SNORM;
				case JinEngine::Graphic::J_GRAPHIC_RESOURCE_FORMAT::R8_SINT:
					return DXGI_FORMAT_R8_SINT;
				default:
				{
					//if ((uint)format >= undefinedFormatOffset)
					//	return DXGI_FORMAT((uint)format - undefinedFormatOffset);
					//else
						return DXGI_FORMAT_UNKNOWN;
				}
				}
			}
			static J_GRAPHIC_RESOURCE_FORMAT ConvertEngine(const DXGI_FORMAT format)
			{
				switch (format)
				{ 
				case DXGI_FORMAT_R32G32B32A32_FLOAT:
					return J_GRAPHIC_RESOURCE_FORMAT::R32G32B32A32_FLOAT;
				case DXGI_FORMAT_R32G32B32A32_UINT:
					return J_GRAPHIC_RESOURCE_FORMAT::R32G32B32A32_UINT;
				case DXGI_FORMAT_R32G32B32A32_SINT:
					return J_GRAPHIC_RESOURCE_FORMAT::R32G32B32A32_SINT;
				case DXGI_FORMAT_R32G32B32_FLOAT:
					return J_GRAPHIC_RESOURCE_FORMAT::R32G32B32_FLOAT;
				case DXGI_FORMAT_R32G32B32_UINT:
					return J_GRAPHIC_RESOURCE_FORMAT::R32G32B32_UINT;
				case DXGI_FORMAT_R32G32B32_SINT:
					return J_GRAPHIC_RESOURCE_FORMAT::R32G32B32_SINT; 
				case DXGI_FORMAT_R16G16B16A16_FLOAT:
					return J_GRAPHIC_RESOURCE_FORMAT::R16G16B16A16_FLOAT;
				case DXGI_FORMAT_R16G16B16A16_UNORM:
					return J_GRAPHIC_RESOURCE_FORMAT::R16G16B16A16_UNORM;
				case DXGI_FORMAT_R16G16B16A16_UINT:
					return J_GRAPHIC_RESOURCE_FORMAT::R16G16B16A16_UINT;
				case DXGI_FORMAT_R16G16B16A16_SNORM:
					return J_GRAPHIC_RESOURCE_FORMAT::R16G16B16A16_SNORM;
				case DXGI_FORMAT_R16G16B16A16_SINT:
					return J_GRAPHIC_RESOURCE_FORMAT::R16G16B16A16_SINT;
				case DXGI_FORMAT_R32G32_FLOAT:
					return J_GRAPHIC_RESOURCE_FORMAT::R32G32_FLOAT;
				case DXGI_FORMAT_R32G32_UINT:
					return J_GRAPHIC_RESOURCE_FORMAT::R32G32_UINT;
				case DXGI_FORMAT_R32G32_SINT:
					return J_GRAPHIC_RESOURCE_FORMAT::R32G32_SINT;
				case DXGI_FORMAT_R10G10B10A2_UNORM:
					return J_GRAPHIC_RESOURCE_FORMAT::R10G10B10A2_UNORM;
				case DXGI_FORMAT_R10G10B10A2_UINT:
					return J_GRAPHIC_RESOURCE_FORMAT::R10G10B10A2_UINT;
				case DXGI_FORMAT_R11G11B10_FLOAT:
					return J_GRAPHIC_RESOURCE_FORMAT::R11G11B10_FLOAT;
				case DXGI_FORMAT_R8G8B8A8_UNORM:
					return J_GRAPHIC_RESOURCE_FORMAT::R8G8B8A8_UNORM;
				case DXGI_FORMAT_R8G8B8A8_UINT:
					return J_GRAPHIC_RESOURCE_FORMAT::R8G8B8A8_UINT;
				case DXGI_FORMAT_R8G8B8A8_SNORM:
					return J_GRAPHIC_RESOURCE_FORMAT::R8G8B8A8_SNORM;
				case DXGI_FORMAT_R8G8B8A8_SINT:
					return J_GRAPHIC_RESOURCE_FORMAT::R8G8B8A8_SINT;
				case DXGI_FORMAT_R16G16_FLOAT:
					return J_GRAPHIC_RESOURCE_FORMAT::R16G16_FLOAT;
				case DXGI_FORMAT_R16G16_UNORM:
					return J_GRAPHIC_RESOURCE_FORMAT::R16G16_UNORM;
				case DXGI_FORMAT_R16G16_UINT:
					return J_GRAPHIC_RESOURCE_FORMAT::R16G16_UINT;
				case DXGI_FORMAT_R16G16_SNORM:
					return J_GRAPHIC_RESOURCE_FORMAT::R16G16_SNORM;
				case DXGI_FORMAT_R16G16_SINT:
					return J_GRAPHIC_RESOURCE_FORMAT::R16G16_SINT;
				case DXGI_FORMAT_D32_FLOAT:
					return J_GRAPHIC_RESOURCE_FORMAT::D32_FLOAT;
				case DXGI_FORMAT_R32_FLOAT:
					return J_GRAPHIC_RESOURCE_FORMAT::R32_FLOAT;
				case DXGI_FORMAT_R32_UINT:
					return J_GRAPHIC_RESOURCE_FORMAT::R32_UINT;
				case DXGI_FORMAT_R32_SINT:
					return J_GRAPHIC_RESOURCE_FORMAT::R32_SINT;
				case DXGI_FORMAT_D24_UNORM_S8_UINT:
					return J_GRAPHIC_RESOURCE_FORMAT::D24_S8;
				case DXGI_FORMAT_R24_UNORM_X8_TYPELESS:
					return J_GRAPHIC_RESOURCE_FORMAT::D24_S8;
				case DXGI_FORMAT_R8G8_UNORM:
					return J_GRAPHIC_RESOURCE_FORMAT::R8G8_UNORM;
				case DXGI_FORMAT_R8G8_UINT:
					return J_GRAPHIC_RESOURCE_FORMAT::R8G8_UINT;
				case DXGI_FORMAT_R8G8_SNORM:
					return J_GRAPHIC_RESOURCE_FORMAT::R8G8_SNORM;
				case DXGI_FORMAT_R8G8_SINT:
					return J_GRAPHIC_RESOURCE_FORMAT::R8G8_SINT;
				case DXGI_FORMAT_R16_FLOAT:
					return J_GRAPHIC_RESOURCE_FORMAT::R16_FLOAT;
				case DXGI_FORMAT_D16_UNORM:
					return J_GRAPHIC_RESOURCE_FORMAT::D16_UNORM;
				case DXGI_FORMAT_R16_UNORM:
					return J_GRAPHIC_RESOURCE_FORMAT::R16_UNORM;
				case DXGI_FORMAT_R16_UINT:
					return J_GRAPHIC_RESOURCE_FORMAT::R16_UINT;
				case DXGI_FORMAT_R16_SNORM:
					return J_GRAPHIC_RESOURCE_FORMAT::R16_SNORM;
				case DXGI_FORMAT_R16_SINT:
					return J_GRAPHIC_RESOURCE_FORMAT::R16_SINT;
				case DXGI_FORMAT_R8_UNORM:
					return J_GRAPHIC_RESOURCE_FORMAT::R8_UNORM;
				case DXGI_FORMAT_R8_UINT:
					return J_GRAPHIC_RESOURCE_FORMAT::R8_UINT;
				case DXGI_FORMAT_R8_SNORM:
					return J_GRAPHIC_RESOURCE_FORMAT::R8_SNORM;
				case DXGI_FORMAT_R8_SINT:
					return J_GRAPHIC_RESOURCE_FORMAT::R8_SINT;
				default:
					return J_GRAPHIC_RESOURCE_FORMAT::API_SPECIALIZED;
					//return (J_GRAPHIC_RESOURCE_FORMAT)(undefinedFormatOffset + format);
				}
			}
		};
	 
	}
}