#pragma once
#include"../Core/Reflection/JReflection.h"

namespace JinEngine
{	
	REGISTER_ENUM_CLASS(J_OBJECT_TYPE, int, GAME_OBJECT,
		COMPONENT_OBJECT,
		RESOURCE_OBJECT,
		DIRECTORY_OBJECT,
		EDITOR_OBJECT);

	/*
	enum class J_OBJECT_TYPE
	{  
		GAME_OBJECT,
		COMPONENT_OBJECT,
		RESOURCE_OBJECT,
		DIRECTORY_OBJECT,
		EDITOR_OBJECT
	};*/
}
