#pragma once
#ifdef USE_3x3_KERNEL
#define KERNEL_RADIUS 1
#elif USE_5x5_KERNEL
#define KERNEL_RADIUS 2
#elif USE_7x7_KERNEL
#define KERNEL_RADIUS 3
#elif USE_2x2_KERNEL
#define KERNEL_RADIUS 1
#define KERNEL_COUNT_IS_EVEN_NUMBER 1
#else 
#define KERNEL_RADIUS 1
#endif

#ifdef KERNEL_COUNT_IS_EVEN_NUMBER
#define KERNEL_SIZE KERNEL_RADIUS * 2
#define KERNEL_START -KERNEL_RADIUS + 1
#define KERNEL_END KERNEL_RADIUS
#define KERNEL_OFFSET KERNEL_RADIUS - 1
#else
#define KERNEL_SIZE KERNEL_RADIUS * 2 + 1
#define KERNEL_START -KERNEL_RADIUS
#define KERNEL_END KERNEL_RADIUS
#define KERNEL_OFFSET KERNEL_RADIUS
#endif

#ifndef KERNEL_MAX_SIZE 
#define KERNEL_MAX_SIZE 7
#endif
 