#pragma once
namespace JinEngine
{
	enum class EDITOR_POPUP_NODE_TYPE
	{
		ROOT,
		INTERNAL,
		LEAF_SELECT,
		LEAF_TOGGLE,
		LEAF_CHECK_BOX
	};
	enum class EDITOR_POPUP_NODE_RES
	{
		NON_CLICK,
		CLICK_SLELECT_NODE,
		CLICK_TOGGLE_TO_ON,
		CLICK_TOGGLE_TO_OFF,
	};
}