#pragma once
#include"JShaderFunctionEnum.h"
#include"../../JObjectFlag.h"

namespace JinEngine
{
	enum class J_DEFAULT_SHADER
	{
		DEFAULT_SHADER,
		DEFAULT_STANDARD_SHADER,
		DEFAULT_SKY_SHADER,
		DEFAULT_SHADOW_MAP_SHADER,
		DEFAULT_DEBUG_LINE_SHADER,
		COUNTER,
	}; 
			
	namespace DefaultShader
	{
		static J_SHADER_FUNCTION GetShaderFunction(const J_DEFAULT_SHADER sType)
		{
			switch (sType)
			{
			case JinEngine::J_DEFAULT_SHADER::DEFAULT_SHADER:
				return SHADER_FUNCTION_NONE;
			case JinEngine::J_DEFAULT_SHADER::DEFAULT_STANDARD_SHADER:
				return (J_SHADER_FUNCTION)(SHADER_FUNCTION_SHADOW | SHADER_FUNCTION_LIGHT);
			case JinEngine::J_DEFAULT_SHADER::DEFAULT_SKY_SHADER:
				return SHADER_FUNCTION_SKY;
			case JinEngine::J_DEFAULT_SHADER::DEFAULT_SHADOW_MAP_SHADER:
				return (J_SHADER_FUNCTION)(SHADER_FUNCTION_ALPHA_CLIP | SHADER_FUNCTION_SHADOW_MAP);
			case JinEngine::J_DEFAULT_SHADER::DEFAULT_DEBUG_LINE_SHADER:
				return SHADER_FUNCTION_DEBUG;
			default:
				break;
			}
		}
		static J_OBJECT_FLAG GetObjectFlag(const J_DEFAULT_SHADER sType)
		{
			switch (sType)
			{
			case JinEngine::J_DEFAULT_SHADER::DEFAULT_SHADER:
				return (J_OBJECT_FLAG)(OBJECT_FLAG_AUTO_GENERATED | OBJECT_FLAG_UNEDITABLE | OBJECT_FLAG_UNDESTROYABLE | OBJECT_FLAG_HIDDEN);
			case JinEngine::J_DEFAULT_SHADER::DEFAULT_STANDARD_SHADER:
				return (J_OBJECT_FLAG)(OBJECT_FLAG_AUTO_GENERATED | OBJECT_FLAG_UNEDITABLE | OBJECT_FLAG_UNDESTROYABLE);
			case JinEngine::J_DEFAULT_SHADER::DEFAULT_SKY_SHADER:
				return (J_OBJECT_FLAG)(OBJECT_FLAG_AUTO_GENERATED | OBJECT_FLAG_UNEDITABLE | OBJECT_FLAG_UNDESTROYABLE);
			case JinEngine::J_DEFAULT_SHADER::DEFAULT_SHADOW_MAP_SHADER:
				return (J_OBJECT_FLAG)(OBJECT_FLAG_AUTO_GENERATED | OBJECT_FLAG_UNEDITABLE | OBJECT_FLAG_UNDESTROYABLE | OBJECT_FLAG_HIDDEN);
			case JinEngine::J_DEFAULT_SHADER::DEFAULT_DEBUG_LINE_SHADER:
				return (J_OBJECT_FLAG)(OBJECT_FLAG_AUTO_GENERATED | OBJECT_FLAG_UNEDITABLE | OBJECT_FLAG_UNDESTROYABLE | OBJECT_FLAG_HIDDEN);
			default:
				return OBJECT_FLAG_NONE;
			}
		}
	}
 
}