#pragma once
#include"../../Core/Reflection/JReflection.h"

namespace JinEngine
{
	REGISTER_ENUM_CLASS(J_COMPONENT_TYPE, int, USER_DEFIENED_BEHAVIOR,
		ENGINE_DEFIENED_ANIMATOR,
		ENGINE_DEFIENED_CAMERA,
		ENGINE_DEFIENED_LIGHT,
		ENGINE_DEFIENED_RENDERITEM,
		ENGINE_DEFIENED_TRANSFORM);

	REGISTER_ENUM_CLASS(COMPONET_ALIGN_TYPE, int, NONE = 0,
		NAME);
}