#pragma once
namespace JinEngine
{
	enum J_RENDERITEM_SPACE_SPATIAL_MASK
	{
		SPACE_SPATIAL_NOT_ALLOW_ALL = 0,
		SPACE_SPATIAL_ALLOW_BUILD = 1 << 0,
		SPACE_SPATIAL_ALLOW_CULLING = 1 << 1,

		SPACE_SPATIAL_ALLOW_ALL = SPACE_SPATIAL_ALLOW_BUILD | SPACE_SPATIAL_ALLOW_CULLING
	};
}