#pragma once
namespace JinEngine
{
	namespace Editor
	{
		enum class J_EDITOR_WINDOW_TYPE
		{
			AVATAR_EDITOR,
			WINDOW_DIRECTORY,
			LOG_VIEWER,
			ANIMATION_CONTROLLER_EDITOR, 
			GRAPHIC_WATCHER,
			OBJECT_EXPLORER,
			OBJECT_DETAIL,
			SCENE_VIEWER,
			SCENE_OBSERVER,
			PROJECT_SELECTOR_HUB,
			DEBUG_APP_ELAPSED_TIME,
			TEST_WINDOW
		};
	}
}