#pragma once
namespace JinEngine
{
	enum class J_AVATAR_JOINT
	{
		ROOT, HIPS, SPINE, CHEST, UPPER_CHEST,
		LEFT_SHOULDER, LEFT_UPPER_ARM, LEFT_LOWER_ARM, LEFT_LOWER_ARM_TWIST, LEFT_UPPER_ARM_TWIST, LEFT_HAND,
		RIGHT_SHOULDER, RIGHT_UPPER_ARM, RIGHT_LOWER_ARM, RIGHT_LOWER_ARM_TWIST, RIGHT_UPPER_ARM_TWIST, RIGHT_HAND,
		LEFT_UPPER_LEG, LEFT_LOWER_LEG, LEFT_CALF_TWIST, LEFT_FOOT, LEFT_TOES, LEFT_THIGH_TWIST,
		RIGHT_UPPER_LEG, RIGHT_LOWER_LEG, RIGHT_CALF_TWIST, RIGHT_FOOT, RIGHT_TOES, RIGHT_THIGH_TWIST,
		LEFT_THUMB_PROXIMAL, LEFT_THUMB_INTERMEDIATE, LEFT_THUMB_DISTAL,
		LEFT_INDEX_PROXIMAL, LEFT_INDEX_INTERMEDIATE, LEFT_INDEX_DISTAL,
		LEFT_MIDDLE_PROXIMAL, LEFT_MIDDLE_INTERMEDIATE, LEFT_MIDDLE_DISTAL,
		LEFT_RING_PROXIMAL, LEFT_RING_INTERMEDIATE, LEFT_RING_DISTAL,
		LEFT_LITTLE_PROXIMAL, LEFT_LITTLE_INTERMEDIATE, LEFT_LITTLE_DISTAL,
		RIGHT_THUMB_PROXIMAL, RIGHT_THUMB_INTERMEDIATE, RIGHT_THUMB_DISTAL,
		RIGHT_INDEX_PROXIMAL, RIGHT_INDEX_INTERMEDIATE, RIGHT_INDEX_DISTAL,
		RIGHT_MIDDLE_PROXIMAL, RIGHT_MIDDLE_INTERMEDIATE, RIGHT_MIDDLE_DISTAL,
		RIGHT_RING_PROXIMAL, RIGHT_RING_INTERMEDIATE, RIGHT_RING_DISTAL,
		RIGHT_LITTLE_PROXIMAL, RIGHT_LITTLE_INTERMEDIATE, RIGHT_LITTLE_DISTAL,

		NECK, HEAD, LEFT_EYE, RIGHT_EYE, JAW,
	};
}