#pragma once
namespace JinEngine
{
	enum class J_COMPONENT_TYPE
	{
		USER_DEFIENED_BEHAVIOR,
		ENGINE_DEFIENED_ANIMATOR,
		ENGINE_DEFIENED_CAMERA,
		ENGINE_DEFIENED_LIGHT,
		ENGINE_DEFIENED_RENDERITEM,
		ENGINE_DEFIENED_TRANSFORM, 
	};	 
}