#pragma once  
#include"../../Core/Reflection/JReflection.h"
namespace JinEngine
{
	namespace Graphic
	{
		//HZB_OCC_OBJECT count is same as BOUNDING_OBJECT
		REGISTER_ENUM_CLASS(J_UPLOAD_FRAME_RESOURCE_TYPE, int, OBJECT, 
			SCENE_PASS,
			ANIMATION,
			CAMERA,
			BOUNDING_OBJECT,	//this frame count is same as OBJECT
			MATERIAL,
			DIRECTIONAL_LIGHT,
			CASCADE_SHADOW_MAP_INFO,
			POINT_LIGHT,
			SPOT_LIGHT,
			RECT_LIGHT,
			SHADOW_MAP_ARRAY_DRAW,
			SHADOW_MAP_CUBE_DRAW,
			SHADOW_MAP_DRAW,
			DEPTH_TEST_PASS,
			HZB_OCC_OBJECT,
			HZB_OCC_COMPUTE_PASS,
			LIGHT_CULLING_PASS,
			SSAO_PASS, 
			OBJECT_REF_INFO)

		enum class J_UPLOAD_CAPACITY_CONDITION
		{
			KEEP,
			DOWN_CAPACITY,
			UP_CAPACITY
		};
	}
}