#pragma once
namespace JinEngine
{
	namespace Editor
	{
		enum class J_EDITOR_PAGE_TYPE
		{
			PROJECT_SELECTOR = 0,
			PROJECT_MAIN,
			SKELETON_SETTING,
			ANICONT_SETTING,
			COUNT,
		};

		enum class J_EDITOR_PAGE_PUBLIC_STATE
		{
			INPUT_LOCK,
			MAXIMIZE
		};

		enum J_EDITOR_PAGE_FLAG
		{
			J_EDITOR_PAGE_NONE = 0,
			J_EDITOR_PAGE_IS_MAIN_PAGE = 1 << 0,
			J_EDITOR_PAGE_SUPPORT_DOCK = 1 << 1,
			J_EDITOR_PAGE_SUPPORT_WINDOW_CLOSING = 1 << 2, 
			J_EDITOR_PAGE_SUPPORT_WINDOW_MAXIMIZE = 1 << 3, 
			J_EDITOR_PAGE_SUPPORT_WINDOW_MINIMIZE = 1 << 4,
			J_EDITOR_PAGE_REQUIRE_INIT_OBJECT = 1 << 5
		};
	}
}