#pragma once
#include"../../Core/Reflection/JReflection.h"

namespace JinEngine
{
	REGISTER_ENUM_CLASS(J_RESOURCE_TYPE, int,
		MESH,
		MATERIAL,
		TEXTURE,
		SHADER,
		SCENE,
		SCRIPT,
		SKELETON,
		ANIMATION_CLIP,
		ANIMATION_CONTROLLER);

	REGISTER_ENUM_CLASS(J_RESOURCE_ALIGN_TYPE, short,
		NONE,
		NAME = 1,
		DEPENDENCY = 2,
		DEPENDENCY_REVERSE = 3);
}
