#pragma once
namespace JinEngine
{
	namespace Editor
	{
		enum class J_EDITOR_WINDOW_TYPE
		{
			AVATAR_EDITOR,
			WINDOW_DIRECTORY,
			LOG_VIEWER,
			ANIMATION_CONTROLLER_EDITOR, 
			GRAPHIC_WATCHER,
			OBJECT_EXPLORER,
			OBJECT_DETAIL,
			SCENE_VIEWER,
			SCENE_OBSERVER,
			PROJECT_SELECTOR_HUB,
			DEBUG_APP_ELAPSED_TIME,
			ANIMATION_DIAGRAM_LIST,
			ANIMATION_CONDITION_LIST,
			ANIMATION_STATE_VIEW,
			TEST_WINDOW
		};

		enum J_EDITOR_WINDOW_FLAG
		{
			J_EDITOR_WINDOW_NONE = 0,
			J_EDITOR_WINDOW_SUPROT_DOCK = 1 << 1,
			J_EDITOR_WINDOW_SUPPORT_WINDOW_CLOSING = 1 << 2,
			J_EDITOR_WINDOW_SELECT = 1 << 3,
			J_EDITOR_WINDOW_LISTEN_OTHER_WINDOW_SELECT = 1 << 4,
			J_EDITOR_WINDOW_SUPPORT_POPUP = 1 << 5
		};
	}
}